// Copyright (c) Orbbec Inc. All Rights Reserved.
// Licensed under the MIT License.

#pragma once

#include "Handler.hpp"
#include <vector>
#include <stack>
#include <string>
#include <memory>
#include <functional>

namespace libobsensor {
namespace jsonmodel {

class ConfigEngine;

/**
 * @brief Function type for processing with ConfigEngine and continuing execution afterwards.
 *
 * @param engine Reference to the ConfigEngine instance.
 */
using ContinueFunc = std::function<void(ConfigEngine &)>;

/**
 * @brief Formatting options for ordered JSON text export.
 */
struct OrderedExportOptions {
    std::string         indentation{ "  " };
    bool                enableYAMLCompatibility{ true };
    bool                dropNullPlaceholders{ false };
    unsigned int        realPrecision{ 6 };
    Json::PrecisionType realPrecisionType{ Json::decimalPlaces };
};

/**
 * @brief The central engine responsible for model registration and data flow
 */
class ConfigEngine {
public:
    ConfigEngine();
    virtual ~ConfigEngine();

    /**
     * @brief Defines an object node with a handler in the JSON hierarchy
     *
     * @param key The key identifying this object
     * @param next A callback to define nested child nodes
     * @param handler Optional handler for this object node
     * @param optional Indicates if this object is optional in the input JSON (default: false)
     */
    void addObject(const std::string &key, ContinueFunc next, std::shared_ptr<IObjectHandler> handler, bool optional = false);

    /**
     * @brief Defines an object node without handler in the JSON hierarchy
     *
     * @param key The key identifying this object
     * @param next A callback to define nested child nodes
     * @param optional Indicates if this object is optional in the input JSON (default: false)
     */
    void declareObject(const std::string &key, ContinueFunc next, bool optional = false) {
        return addObject(key, next, nullptr, optional);
    }

    /**
     * @brief Defines a leaf property node with a handler in the JSON hierarchy
     *
     * @param key The key identifying this object
     * @param handler Optional handler for this leaf node
     * @param optional Indicates if this object is optional in the input JSON (default: false)
     */
    void addLeaf(const std::string &key, std::shared_ptr<ILeafHandler> handler, bool optional = false);

    /**
     * @brief Defines a leaf property node without handler in the JSON hierarchy
     *
     * @param key The key identifying this object
     * @param optional Indicates if this object is optional in the input JSON (default: false)
     */
    void declareLeaf(const std::string &key, bool optional = false) {
        return addLeaf(key, nullptr, optional);
    }

    /**
     * @brief Imports data from a JSON object and applies it to registered handlers
     * @param root The source JSON object
     * @throws std::runtime_error If a required path is missing in the JSON
     */
    void importAll(const Json::Value &root);

    /**
     * @brief Exports the current state of all handlers into a JSON object
     * @return The resulting JSON object
     */
    Json::Value exportAll();

    /**
     * @brief Exports the current state as JSON text using declaration order for object members.
     * @param options Formatting options for ordered export
     * @return The resulting JSON string
     */
    std::string exportAll(const OrderedExportOptions &options);

private:
    /**
     * @brief Recursive helper for import (Child-to-Parent execution)
     * @param node Current traversal node
     * @param value The JSON value corresponding to this node
     * @param pathStack The current path stack
     */
    void importRecursive(std::shared_ptr<Node> node, const Json::Value &value, std::vector<std::string> &pathStack);

    /**
     * @brief Recursive helper for export (Parent-to-Child execution)
     * @param node Current traversal node
     * @return The structured export value generated by this node and its children
     */
    ExportValue buildExportValue(const std::shared_ptr<Node> &node);

private:
    std::shared_ptr<Node>             rootNode_;   // The root of the node tree
    std::stack<std::shared_ptr<Node>> nodeStack_;  // Context stack for tree building
};

}  // namespace jsonmodel
}  // namespace libobsensor
